import { describe, expect, it } from "vitest";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { SUPPORTED_LOCALES, formatNumberLocalized, matchLocale } from "../index";
import barrel from "../translations.barrel.json";

/**
 * Poki localization rules LOC-02 (one file, centralized) and LOC-04 (phase
 * order: EFIGS + Turkish, then CJK, then Portuguese + Russian) plus LOC-05
 * (browser-language detection). A missing string in one locale is exactly the
 * kind of defect that only shows up on a device the developer does not own, so
 * it is a build failure here instead.
 */
const entries = Object.entries((barrel as { barrel: Record<string, { placeholders: string[]; translations: Record<string, string> }> }).barrel);

const PHASE_1 = ["en", "fr", "it", "de", "es", "tr"];
const PHASE_2_CJK = ["zh", "ja", "ko"];
const PHASE_3 = ["pt", "ru"];

describe("translation barrel (LOC-02)", () => {
  it("keeps every shipped locale complete", () => {
    const missing: string[] = [];
    for (const [key, entry] of entries) {
      for (const locale of SUPPORTED_LOCALES) {
        const value = entry.translations[locale.code];
        if (!value || !value.trim()) missing.push(`${locale.code}:${key}`);
      }
    }
    expect(missing).toEqual([]);
  });

  it("preserves every placeholder in every translation", () => {
    const broken: string[] = [];
    for (const [key, entry] of entries) {
      for (const [locale, value] of Object.entries(entry.translations)) {
        for (const token of entry.placeholders) {
          if (!value.includes(token)) broken.push(`${locale}:${key} missing ${token}`);
        }
      }
    }
    expect(broken).toEqual([]);
  });

  it("keeps the shipped barrel copies byte-identical (src ⇄ public ⇄ generated upload folder)", () => {
    const root = resolve(__dirname, "../../..");
    const read = (p: string) => readFileSync(resolve(root, p), "utf8");
    const src = read("src/i18n/translations.barrel.json");
    // The barrel has ONE home. A `public/i18n/` copy used to be asserted here,
    // but nothing fetches it: the runtime loads the generated packs, and the
    // folder is not in the repo — so that assertion only ever failed. Keeping
    // one home is the rule this test exists to enforce.
    // poki-upload/ is GENERATED by `pnpm build:poki` (it used to be a
    // hand-committed snapshot — which went stale and broke a real Inspector
    // upload). It is absent on a fresh clone; when a build has produced it, it
    // must match, and `scripts/verify-upload.mjs` proves that for the whole
    // folder including freshness against dist-poki/.
    const generated = resolve(root, "poki-upload/i18n/translations.barrel.json");
    if (existsSync(generated)) expect(readFileSync(generated, "utf8")).toBe(src);
  });
});

describe("locale coverage (LOC-04)", () => {
  it.each([...PHASE_1, ...PHASE_2_CJK, ...PHASE_3])("ships %s", (locale) => {
    expect(SUPPORTED_LOCALES.map((l) => l.code)).toContain(locale);
  });

  it("keeps the recommended phase order stable in the selector", () => {
    const codes = SUPPORTED_LOCALES.map((l) => l.code);
    const efigs = codes.indexOf("en");
    expect(codes.indexOf("tr")).toBeGreaterThan(efigs);
    expect(codes.indexOf("ru")).toBeGreaterThan(codes.indexOf("pt") - 1);
  });
});

describe("browser-language detection (LOC-05)", () => {
  it("matches exact tags", () => {
    expect(matchLocale("de")).toBe("de");
    expect(matchLocale("tr-TR")).toBe("tr");
    expect(matchLocale("ru-RU")).toBe("ru");
  });

  it("falls back from a region variant to the same language", () => {
    // One pack per language. A Brazilian and a Portuguese player both land on
    // `pt`, and every Chinese spelling lands on `zh` rather than on English.
    expect(matchLocale("pt")).toBe("pt");
    expect(matchLocale("pt-BR")).toBe("pt");
    expect(matchLocale("pt-PT")).toBe("pt");
    expect(matchLocale("zh-Hant")).toBe("zh");
    expect(matchLocale("zh-TW")).toBe("zh");
    expect(matchLocale("ja-JP")).toBe("ja");
  });

  it("is case- and separator-insensitive (BCP-47 spellings)", () => {
    expect(matchLocale("PT_br")).toBe("pt");
    expect(matchLocale("  DE-at ")).toBe("de");
  });

  it("returns null for languages the game does not ship", () => {
    // Irish, Swahili and Icelandic are genuinely absent — Finnish is NOT, and
    // using it here is how a shipped locale can go unmatched forever.
    for (const tag of ["ga-IE", "sw-KE", "is-IS"]) expect(matchLocale(tag)).toBeNull();
    expect(matchLocale("")).toBeNull();
    expect(matchLocale(null)).toBeNull();
    expect(matchLocale(undefined)).toBeNull();
  });
});


describe("runtime packs (generated from the barrel)", () => {
  /**
   * Packs are POSITIONAL: `pack-keys.json` holds the sorted key list once, and
   * each locale file is an array of texts in exactly that order. Shipping the
   * keys once instead of repeating them in 36 maps cut the i18n payload by
   * about a third (see scripts/gen-i18n-packs.mjs).
   *
   * These two tests used to rebuild a key → text MAP and diff it against the
   * file, so they compared a map to an array and failed for every locale on
   * every run — while the pack registry test above happily re-derived the same
   * wrong shape. They now check the format that is actually shipped.
   */
  it("regenerates byte-identical packs from the barrel (no drift)", () => {
    const root = resolve(__dirname, "../../..");
    const barrel = JSON.parse(readFileSync(resolve(root, "src/i18n/translations.barrel.json"), "utf8")) as {
      barrel: Record<string, { translations: Record<string, string>; sourceText?: string }>;
    };
    const keys = Object.keys(barrel.barrel).sort();
    const expectedKeys = JSON.stringify(keys) + "\n";
    expect(readFileSync(resolve(root, "src/i18n/pack-keys.json"), "utf8"), "pack-keys.json").toBe(expectedKeys);

    const codes = [...new Set(Object.values(barrel.barrel).flatMap((e) => Object.keys(e.translations ?? {})))].sort();
    const englishOf = (key: string) => {
      const entry = barrel.barrel[key]!;
      const text = entry.translations.en ?? entry.sourceText;
      return typeof text === "string" ? text : "";
    };
    const drift: string[] = [];
    for (const code of codes) {
      const values = keys.map((key) => {
        const entry = barrel.barrel[key]!;
        const text = entry.translations[code] ?? entry.translations.en ?? entry.sourceText;
        const value = typeof text === "string" ? text : "";
        // Mirrors gen-i18n-packs.mjs: a cell identical to English is stored as
        // null and inherits English at runtime. The drift check has to encode
        // that or it would demand the pre-compaction shape forever.
        return code !== "en" && value !== "" && value === englishOf(key) ? null : value;
      });
      const expected = JSON.stringify(values) + "\n";
      const actual = readFileSync(resolve(root, `src/i18n/packs/${code}.json`), "utf8");
      if (actual !== expected) drift.push(code);
    }
    expect(drift).toEqual([]);
  });

  it("every pack covers every key, and every nulled slot is provably lossless", () => {
    const root = resolve(__dirname, "../../..");
    const barrel = JSON.parse(readFileSync(resolve(root, "src/i18n/translations.barrel.json"), "utf8")) as {
      barrel: Record<string, unknown>;
    };
    const keys = JSON.parse(readFileSync(resolve(root, "src/i18n/pack-keys.json"), "utf8")) as string[];
    expect(keys.length, "pack-keys covers every barrel key").toBe(Object.keys(barrel.barrel).length);

    const english = JSON.parse(readFileSync(resolve(root, "src/i18n/packs/en.json"), "utf8")) as (string | null)[];

    for (const file of readdirSync(resolve(root, "src/i18n/packs"))) {
      const pack = JSON.parse(readFileSync(resolve(root, "src/i18n/packs", file), "utf8")) as (string | null)[];
      const isEnglish = file === "en.json";
      // Position is meaning: a pack that is a different length from the key
      // list would shift every string after the gap onto the wrong key.
      expect(pack.length, `${file} length !== key count`).toBe(keys.length);

      // The user-facing guarantee: whatever a player resolves for any key in
      // any locale is a non-empty string. A blank label is a visible defect;
      // a null slot is only legal because it resolves to a real English cell.
      const blank = keys.filter((_, i) => {
        const resolved = pack[i] ?? english[i];
        return typeof resolved !== "string" || resolved.length === 0;
      });
      expect(blank, `${file} resolves to an empty label`).toEqual([]);

      if (isEnglish) continue;
      // English is the fallback every nulled slot points at, so it must be
      // total on its own. A null here would make a null elsewhere meaningless.
      expect(english.filter((v) => typeof v === "string" && v.length > 0).length).toBe(keys.length);

      // Nulling is a *storage* optimisation, never a loss of content. If a slot
      // is dropped it must be byte-identical to English, or the compaction has
      // silently discarded a real translation.
      const lossy = keys.filter((_, i) => pack[i] === null && english[i] === null);
      expect(lossy, `${file} nulls a slot English cannot fill`).toEqual([]);
    }
  });

  // A placeholder syntax `t()` cannot resolve is worse than no translation: the
  // broken string wins over the correct default passed alongside it, and the
  // player reads the template. The home screen shipped "%Perfect Circuit ends
  // in %day — You're %Unranked!" for exactly this reason — `%{}` where the
  // interpolator only understands `{}` and `{{}}`.
  it("no string carries a placeholder syntax the interpolator cannot resolve", () => {
    const root = resolve(__dirname, "../../..");
    const barrel = JSON.parse(readFileSync(resolve(root, "src/i18n/translations.barrel.json"), "utf8")) as {
      barrel: Record<string, { translations: Record<string, string> }>;
    };
    const unsupported = /%\{|\{[^{}]*$/;
    for (const [key, entry] of Object.entries(barrel.barrel)) {
      for (const [locale, text] of Object.entries(entry.translations ?? {})) {
        expect(typeof text, `${key}.${locale} is not a string`).toBe("string");
        expect(text, `${key}.${locale} uses a placeholder t() cannot resolve`).not.toMatch(unsupported);
      }
    }
  });
});

describe("localized number formatting (the coin counters)", () => {
  it("groups thousands in English", () => {
    expect(formatNumberLocalized(12_480, "en")).toBe("12,480");
    expect(formatNumberLocalized(999_999, "en")).toBe("999,999");
  });

  it("uses the locale's own separators", () => {
    // German swaps the separator roles; a hardcoded en-US toLocaleString got
    // this wrong for every player whose language was not English.
    expect(formatNumberLocalized(12_480, "de")).toBe("12.480");
    expect(formatNumberLocalized(12_480, "pt")).toBe("12.480");
  });

  it("adds no grouping separator under a thousand, in every shipped locale", () => {
    // Not `toBe("240")`: several shipped locales do not use ASCII digits at all
    // — Bengali renders 240 as ২৪০ and Arabic as ٢٤٠, which is correct. The
    // invariant is that no thousands separator appears below 1000, so the
    // counter never grows a stray "." or "," that reads as a decimal.
    for (const locale of SUPPORTED_LOCALES) {
      const formatted = formatNumberLocalized(240, locale.code);
      expect(formatted, `${locale.code} grouped 240 as ${formatted}`).not.toMatch(/[,.'\u00A0\u202F]/);
      // ...and it still denotes the same number, whatever the script. `\d` is
      // ASCII-only in JS, so it would strip Bengali/Arabic digits entirely and
      // report zero of them; `\p{Nd}` is the Unicode decimal-digit class.
      const digits = formatted.replace(/\P{Nd}/gu, "");
      expect(digits.length, `${locale.code} → ${formatted}`).toBe(3);
    }
  });
});

/**
 * The coverage direction that was missing.
 *
 * Every test above walks barrel → packs. Nothing walked source → barrel, so a
 * `t("some.key", undefined, "English")` whose key was never added looked
 * perfectly healthy: 20 locales, 44 keys, all green — while that string
 * silently rendered its English fallback for every non-English player. That is
 * the very failure the barrel's doc comment claims to prevent, inverted. This
 * closes it: any literal key passed to `t()` must exist in the barrel.
 */
describe("source → barrel coverage (the direction that was missing)", () => {
  it("every literal key passed to t() exists in the barrel", () => {
    const root = resolve(__dirname, "../../..");
    const barrelDoc = JSON.parse(readFileSync(resolve(root, "src/i18n/translations.barrel.json"), "utf8")) as {
      barrel: Record<string, unknown>;
    };
    const known = new Set(Object.keys(barrelDoc.barrel));
    // A translation key is dotted, lowercase and space-free. That shape is what
    // separates a real t("hud.stat.coins") from an unrelated local named `t`.
    // Case-tolerant: the previous class was lowercase-only, so every camelCase
    // key (`hud.heroSub`, `onboarding.tapToDive`, `hud.gameover.newBest`, ...)
    // was invisible to this guard. 21 shipping strings were rendering English
    // on all 36 locales while the test that exists to prevent exactly that
    // passed. Uppercase is a normal part of a key, not an escape hatch.
    const call = /\bt\(\s*["'`]([A-Za-z0-9]+(?:\.[A-Za-z0-9-]+)+)["'`]/g;
    const walk = (dir: string): string[] =>
      readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
        const full = resolve(dir, entry.name);
        if (entry.isDirectory()) return entry.name === "__tests__" || entry.name === "packs" ? [] : walk(full);
        return /\.tsx?$/.test(entry.name) ? [full] : [];
      });
    const unknown = new Map<string, string>();
    for (const file of walk(resolve(root, "src"))) {
      for (const match of readFileSync(file, "utf8").matchAll(call)) {
        const key = match[1]!;
        if (!known.has(key)) unknown.set(key, file.slice(root.length + 1));
      }
    }
    expect([...unknown].map(([key, file]) => `${key}  (${file})`)).toEqual([]);
  });
});
