/**
 * Renders `public/privacy.html` — the hosted privacy policy — from
 * `src/game/legal.ts`.
 *
 * Why generated rather than hand-written:
 *   • Poki's external-resources policy asks for a policy "hosted on a live
 *     webpage accessible to all players, linked inside the game". Two copies of
 *     a legal document (a page and an in-game screen) drift; one data module
 *     with two renderers cannot.
 *   • The in-game Settings → Privacy screen renders the same `PRIVACY_POLICY`
 *     object, so a reviewer comparing the URL they were given with what a
 *     player sees inside the iframe is comparing one document to itself.
 *
 * The page is deliberately self-contained: no stylesheet link, no script, no
 * font, no analytics, no external request of any kind. It has to load for a
 * player who reached it from a portal iframe on a phone, and a policy page that
 * phones home would contradict its own contents.
 *
 *     pnpm gen-legal          # regenerate
 * `src/game/__tests__/legal.test.ts` re-renders in memory and fails on drift.
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { composePolicy, PRIVACY_POLICY_VERSION, type LegalEdition } from "../src/game/legal";
// The hosted page is the UNION of every edition's disclosures: a reviewer given
// this URL cannot know which build a player will use, and a player reading it
// should be able to find their own edition. Each bundle, by contrast, imports
// only its own `legal.edition.*` file (aliased in vite.config.ts), so no portal
// ships another portal's host names.
import { LEGAL_EDITION as WEB_EDITION } from "../src/game/legal.edition";
import { LEGAL_EDITION as POKI_EDITION } from "../src/game/legal.edition.poki";
import { LEGAL_EDITION as CRAZY_EDITION } from "../src/game/legal.edition.crazy";
import { LEGAL_EDITION as GENERIC_EDITION } from "../src/game/legal.edition.generic";

const EDITIONS: LegalEdition[] = [POKI_EDITION, CRAZY_EDITION, GENERIC_EDITION, WEB_EDITION];
const PRIVACY_POLICY = composePolicy(EDITIONS);

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "public/privacy.html");

const esc = (value: string): string =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

const rows = (list: [string, string][]): string =>
  `<dl>${list.map(([k, v]) => `<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join("\n")}</dl>`;

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="index,follow" />
<meta name="description" content="${esc(PRIVACY_POLICY.game)} privacy policy — what the game stores, what it can send, and how to delete it." />
<title>${esc(PRIVACY_POLICY.title)} — ${esc(PRIVACY_POLICY.game)}</title>
<!-- Generated by scripts/gen-privacy-page.ts from src/game/legal.ts. Do not edit
     this file: edit the data module and regenerate, or the in-game copy of the
     policy (Settings → Privacy Policy) will disagree with this page. -->
<style>
:root { color-scheme: light; }
* { box-sizing: border-box; }
body {
  margin: 0; padding: 32px 20px 64px; background: #fff6e8; color: #2a1c28;
  font: 16px/1.6 "Trebuchet MS", "Segoe UI", system-ui, sans-serif;
}
main { max-width: 720px; margin: 0 auto; }
h1 { font-size: 28px; line-height: 1.2; margin: 0 0 4px; }
.meta { font-size: 13px; color: #7a655c; margin: 0 0 20px; }
.lede { font-size: 17px; line-height: 1.55; margin: 0 0 12px; }
section { margin: 0 0 22px; }
h2 { font-size: 18px; margin: 0 0 8px; }
p { margin: 0 0 10px; }
dl { display: grid; grid-template-columns: minmax(150px, 32%) 1fr; gap: 6px 14px; margin: 10px 0 0; }
dt { font-weight: 700; }
dd { margin: 0; }
footer { border-top: 1px solid #e3d3c2; margin-top: 28px; padding-top: 14px; font-size: 13px; color: #7a655c; }
code { background: #f4e7d6; padding: 1px 5px; border-radius: 4px; font-size: 14px; }
@media (max-width: 560px) {
  dl { grid-template-columns: 1fr; gap: 2px 0; }
  dd { margin: 0 0 8px; }
}
</style>
</head>
<body>
<main>
<h1>${esc(PRIVACY_POLICY.title)}</h1>
<p class="meta">${esc(PRIVACY_POLICY.game)} · ${esc(PRIVACY_POLICY.controller)} · version ${esc(PRIVACY_POLICY_VERSION)}</p>
${PRIVACY_POLICY.summary.map((p) => `<p class="lede">${esc(p)}</p>`).join("\n")}
${PRIVACY_POLICY.sections
  .map(
    (sec) => `<section id="${esc(sec.id)}">
<h2>${esc(sec.heading)}</h2>
${sec.body.map((p) => `<p>${esc(p)}</p>`).join("\n")}
${sec.rows ? rows(sec.rows) : ""}
</section>`,
  )
  .join("\n")}
<section id="contact">
<h2>Contact</h2>
${rows(PRIVACY_POLICY.contact.map((c) => [c.label, c.value] as [string, string]))}
</section>
<footer>
<p>This page is generated from the same source the game renders in
<code>Settings → Privacy Policy</code>, so the two can never disagree. If you
find a difference, that is a bug — please report it.</p>
</footer>
</main>
</body>
</html>
`;

const before = existsSync(out) ? readFileSync(out, "utf8") : null;
writeFileSync(out, html, "utf8");
const sections = PRIVACY_POLICY.sections.length;
const detailRows = PRIVACY_POLICY.sections.reduce((n, s) => n + (s.rows?.length ?? 0), 0);
console.log(
  `privacy.html — ${Buffer.byteLength(html)} bytes · ${sections} sections · ${detailRows} detail rows` +
    (before === html ? " (unchanged)" : before === null ? " (new)" : " (updated)"),
);
