import { afterEach, describe, expect, it, vi } from "vitest";
import { buildRoomInviteUrl, normalizeRoomCode } from "../DeepLinks";

describe("room invite deep links", () => {
  it("normalizes input to a 5-char code", () => {
    expect(normalizeRoomCode("abc12")).toBe("ABC12");
    expect(normalizeRoomCode("  a-bc1-2 ")).toBe("ABC12");
    expect(normalizeRoomCode("abc12zzz")).toBe("ABC12"); // truncated to 5
  });

  it("strips non-alphanumerics before validating", () => {
    expect(normalizeRoomCode("a!b@c#1$2")).toBe("ABC12");
  });

  it("rejects input with fewer than 4 usable characters", () => {
    expect(normalizeRoomCode("abc")).toBe("");
    expect(normalizeRoomCode("")).toBe("");
    expect(normalizeRoomCode("!!")).toBe("");
  });

  /**
   * REGRESSION: the signalling service mints FOUR-character codes even though
   * `createRoom` asks for `codeLength: 5` ("4FN7", "TWD6", "C7JH" observed
   * live). This normalizer used to require exactly five, so `createRoom`'s
   * code — which the host path adopts verbatim — was rejected by `join-room`
   * with "Enter a 5-letter room code". The host always got a room; the guest
   * could never enter it.
   */
  it("accepts a 4-char code as minted by the Netlib signalling service", () => {
    expect(normalizeRoomCode("4fn7")).toBe("4FN7");
    expect(normalizeRoomCode(" twd6 ")).toBe("TWD6");
    // The 5-char form (locally generated by makePokiRoomCode) still works.
    expect(normalizeRoomCode("ABC12")).toBe("ABC12");
  });

  it("accepts a pasted invite without converting HTTPS into a room", () => {
    expect(normalizeRoomCode("https://game.example/play#room=abc12")).toBe("ABC12");
    expect(normalizeRoomCode("#room=ABC12&rival=other")).toBe("ABC12");
    expect(normalizeRoomCode("https://game.example/play")).toBe("");
    expect(normalizeRoomCode("https://game.example/#other=ABCDE")).toBe("");
  });
  it("builds a shareable URL", () => {
    expect(buildRoomInviteUrl("abc12")).toMatch(/#room=ABC12$/);
    expect(buildRoomInviteUrl("bad")).toMatch(/#room=BAD$/);
  });

  it("parses and consumes a #room= invite exactly once", async () => {
    vi.resetModules();
    const { readRoomInviteFromUrl } = await import("../DeepLinks");
    window.location.hash = "#room=XYZ12";
    expect(readRoomInviteFromUrl()).toBe("XYZ12");
    expect(readRoomInviteFromUrl()).toBe("XYZ12"); // already consumed this session
    expect(window.location.hash).not.toContain("room=");
  });

  it("ignores a hash without a room code", async () => {
    vi.resetModules();
    const { readRoomInviteFromUrl } = await import("../DeepLinks");
    window.location.hash = "#rival=a.b.c";
    expect(readRoomInviteFromUrl()).toBeNull();
  });

  afterEach(() => {
    window.location.hash = "";
  });
});
